"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const circle_1 = require("./circle");
const rectangles_1 = require("./rectangles");
let mycircle = new circle_1.Circle(3, 10, 20);
console.log(mycircle.getInfo());
console.log(mycircle.calculateArea());
console.log("-------------------");
let myRectangle = new rectangles_1.Rectangle(5, 10, 15, 20);
console.log(myRectangle.getInfo());
console.log(myRectangle.calculateArea());
